project:
  type: website
  output-dir: docs
  
website:
  title: "Testowa Super Strona"
  navbar:
    left:
      - href: index.qmd
        text: Home
        pub.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



